export type Locale = 'fr' | 'ar'
export type Localized = { fr: string; ar: string }
export const pick = (value: Localized, locale: Locale) => value[locale]

export const ui = {
  fr: {
    home: 'Accueil', courses: 'Cours', plan: 'Planning', progress: 'Progrès', coach: 'Coach', resources: 'Ressources', online: 'En ligne', offline: 'Hors ligne',
    library: 'Bibliothèque BAC', libraryTitle: 'Cours & exercices', libraryText: 'Apprends avec une fiche structurée, pratique sans regarder la correction puis évalue ta maîtrise.', search: 'Rechercher un chapitre…', all: 'Toutes les matières', guide: 'Guide pratique', read: 'Maîtrisé', minutes: 'min', sheet: 'fiche', exercises: 'exercices', back: 'Retour à la bibliothèque', objectives: 'Objectifs mesurables', prerequisites: 'Prérequis', essentials: 'Notions essentielles', method: 'Méthode pas à pas', example: 'Exemple guidé', mistakes: 'Erreurs fréquentes', recap: 'Résumé express', mastered: 'Chapitre maîtrisé', markMastered: 'Marquer comme maîtrisé', practice: 'Entraînement progressif', hint: 'Voir un indice', correction: 'Afficher la correction', hideCorrection: 'Masquer la correction', yourAnswer: 'Écris ta réponse ou ton raisonnement…', succeeded: 'J’ai réussi', review: 'À revoir', printCourse: 'Télécharger le cours', printExercises: 'Télécharger exercices + corrigés', printPack: 'Télécharger le pack matière', official: 'Ressources officielles', connection: 'Connexion requise', verified: 'Vérifié', open: 'Ouvrir la source', originalNotice: 'Contenus originaux de révision, alignés sur les thèmes publics. Vérifiez les éventuelles évolutions auprès de votre établissement.',
    hello: 'Bonjour', ready: 'Prêt à progresser ?', todayText: 'Une micro-session active vaut mieux qu’une longue lecture passive.', mastery: 'maîtrisé', lessonsRead: 'chapitres', attempts: 'tentatives', sessions: 'séances', today: 'Aujourd’hui', dailyProgram: 'Ta micro-session', viewPlan: 'Voir le planning', resume: 'Reprendre un cours', seeAll: 'Tout voir', streak: 'Série actuelle', days: 'jours', regularity: 'Régularité', regularityText: 'Rappelle-toi, pratique, explique : trois gestes simples chaque jour.', week: 'Semaine personnalisée', myPlan: 'Mon planning', weeklyGoal: 'Objectif hebdomadaire', globalProgress: 'Progression globale', bySubject: 'Par matière', reset: 'Réinitialiser', course: 'Cours', exercise: 'Exercice', setup: 'Configuration', chooseStream: 'Choisis ta filière', priorities: 'Tes matières prioritaires', rhythm: 'Ton rythme de travail', continue: 'Continuer', create: 'Créer mon espace', previous: 'Retour', name: 'Ton prénom (facultatif)', dailyTime: 'Temps disponible chaque jour', coefficient: 'Coefficient indicatif', local: '100 % local · disponible hors ligne', hero: 'Ton BAC, préparé avec une méthode claire.', heroText: 'Cours bilingues, exercices corrigés, planning adaptatif et guide pratique pour les filières mauritaniennes.', streams: 'filières', subjects: 'matières', guided: 'jours guidés', coachTitle: 'Coach de révision', coachText: 'Conseils pratiques disponibles hors ligne.', ask: 'Pose ta question…', send: 'Envoyer', reviewedToday: 'As-tu révisé aujourd’hui ?', yes: 'Oui', no: 'Non', dailyPrompt: 'Réponds honnêtement, sans pression.', sourceTitle: 'Cadre pédagogique', empty: 'Aucun chapitre ne correspond à ta recherche.', level: 'Fondamental', step: 'Étape', of: 'sur', setupTime: 'Configuration en 2 minutes', chooseTwo: 'Sélectionne au moins deux matières.', modifyLater: 'Tu pourras modifier ce choix plus tard.', realistic: 'Un objectif réaliste aide à rester régulier.', importExport: 'Importer / Exporter', importText: 'Importez vos propres cours et exercices (avec corrections) depuis un fichier JSON, ou exportez le contenu existant.', importFile: 'Importer un fichier JSON', downloadTemplate: 'Télécharger le modèle', exportSubject: 'Exporter une matière', exportText: 'Téléchargez une matière au format JSON pour la partager ou la réimporter.', importedChapters: 'Mes cours importés', importSuccess: 'Cours importés avec succès.', importError: 'Fichier invalide. Vérifiez le format JSON.', delete: 'Supprimer', chapters: 'chapitre(s)'
  },
  ar: {
    home: 'الرئيسية', courses: 'الدروس', plan: 'البرنامج', progress: 'التقدم', coach: 'المدرب', resources: 'المصادر', online: 'متصل', offline: 'دون اتصال',
    library: 'مكتبة البكالوريا', libraryTitle: 'الدروس والتمارين', libraryText: 'تعلّم من ملخص منظم، ثم طبّق دون النظر إلى الحل وقيّم مستوى إتقانك.', search: 'ابحث عن فصل…', all: 'جميع المواد', guide: 'الدليل العملي', read: 'متقن', minutes: 'د', sheet: 'ملخص', exercises: 'تمارين', back: 'العودة إلى المكتبة', objectives: 'أهداف قابلة للقياس', prerequisites: 'المكتسبات القبلية', essentials: 'المفاهيم الأساسية', method: 'منهجية خطوة بخطوة', example: 'مثال محلول', mistakes: 'أخطاء شائعة', recap: 'خلاصة سريعة', mastered: 'تم إتقان الفصل', markMastered: 'تحديد الفصل كمتقن', practice: 'تدريب متدرج', hint: 'عرض تلميح', correction: 'عرض التصحيح', hideCorrection: 'إخفاء التصحيح', yourAnswer: 'اكتب إجابتك أو خطوات تفكيرك…', succeeded: 'أجبت بشكل صحيح', review: 'أحتاج إلى المراجعة', printCourse: 'تنزيل الدرس', printExercises: 'تنزيل التمارين والتصحيح', printPack: 'تنزيل حزمة المادة', official: 'المصادر الرسمية', connection: 'يتطلب الاتصال', verified: 'آخر تحقق', open: 'فتح المصدر', originalNotice: 'محتويات مراجعة أصلية متوافقة مع المحاور المنشورة. يُرجى التحقق من أي تحديثات لدى المؤسسة.',
    hello: 'مرحبا', ready: 'هل أنت مستعد للتقدم؟', todayText: 'حصة قصيرة نشطة أفضل من قراءة طويلة سلبية.', mastery: 'إتقان', lessonsRead: 'فصول', attempts: 'محاولات', sessions: 'حصص', today: 'اليوم', dailyProgram: 'حصتك المصغرة', viewPlan: 'عرض البرنامج', resume: 'تابع درسا', seeAll: 'عرض الكل', streak: 'السلسلة الحالية', days: 'أيام', regularity: 'الاستمرارية', regularityText: 'استرجع، طبّق، اشرح: ثلاث عادات بسيطة كل يوم.', week: 'أسبوع مخصص', myPlan: 'برنامجي', weeklyGoal: 'هدف الأسبوع', globalProgress: 'التقدم العام', bySubject: 'حسب المادة', reset: 'إعادة الضبط', course: 'درس', exercise: 'تمرين', setup: 'الإعداد', chooseStream: 'اختر شعبتك', priorities: 'موادك ذات الأولوية', rhythm: 'وتيرة عملك', continue: 'متابعة', create: 'إنشاء مساحتي', previous: 'رجوع', name: 'الاسم (اختياري)', dailyTime: 'الوقت المتاح يوميا', coefficient: 'المعامل الاسترشادي', local: 'محلي بالكامل · يعمل دون إنترنت', hero: 'استعد للبكالوريا بمنهجية واضحة.', heroText: 'دروس ثنائية اللغة، تمارين مصححة، برنامج متكيف ودليل عملي للشعب الموريتانية.', streams: 'شعب', subjects: 'مواد', guided: 'أيام موجهة', coachTitle: 'مدرب المراجعة', coachText: 'نصائح عملية متاحة دون اتصال.', ask: 'اكتب سؤالك…', send: 'إرسال', reviewedToday: 'هل راجعت اليوم؟', yes: 'نعم', no: 'لا', dailyPrompt: 'أجب بصراحة ودون ضغط.', sourceTitle: 'الإطار التربوي', empty: 'لا يوجد فصل مطابق للبحث.', level: 'أساسي', step: 'الخطوة', of: 'من', setupTime: 'إعداد في دقيقتين', chooseTwo: 'اختر مادتين على الأقل.', modifyLater: 'يمكنك تغيير اختيارك لاحقا.', realistic: 'يساعدك الهدف الواقعي على الاستمرار.', importExport: 'استيراد / تصدير', importText: 'استورد دروسك وتمارينك (مع التصحيح) من ملف JSON، أو صدّر المحتوى الحالي.', importFile: 'استيراد ملف JSON', downloadTemplate: 'تنزيل النموذج', exportSubject: 'تصدير مادة', exportText: 'نزّل مادة بصيغة JSON لمشاركتها أو إعادة استيرادها.', importedChapters: 'دروسي المستوردة', importSuccess: 'تم استيراد الدروس بنجاح.', importError: 'ملف غير صالح. تحقق من تنسيق JSON.', delete: 'حذف', chapters: 'فصل/فصول'
  }
} as const
